### ISSUE TITLE
入职第一天

### ISSUE THREAD

**Issue by d87335903** [xiaoxinlma/a-day-of-a-programmer#1]
那那那!其实我是一名“程序员”!http://search.jd.com/Search?keyword=sql%20server&enc=utf-8&qrst=1&stop=1&vt=2&wq=sqlserver&psort=3&click=0

**Comment by xiaoxinlma** [comment]
平台终于MD搭好了

**Comment by xiaoxinlma** [comment]
日你哥，你在干嘛呢

**Comment by d87335903** [comment]
在jd上给你找sqlserver的书呀!

**Comment by xiaoxinlma** [comment]
牛逼，找一上午，你直接找一天吧
