### ISSUE TITLE
共勉

### ISSUE THREAD

**Issue by d87335903** [xiaoxinlma/a-day-of-a-programmer#2]
既然当初选择了安逸懒惰，那就好好承受今天所遭遇的平庸艰难；若是心中仍有不甘，那就从现在起发奋图强。有时候世界就是这么公平。若是一边继续保持懒惰安乐，一边又期望自己未来能功成名就，觉得世界应该偏爱自己，那你咋不上天呢～

**Comment by d87335903** [comment]
什么时候都不晚,晚的是你不敢开始

**Comment by d87335903** [comment]
当处在低谷时一定要清醒，要忍耐，要淡定。这是生活给你一个难得的自省机会，利用这些时间多学习、暗地里提高自己，为即将到来的高峰做准备！

**Comment by xiaoxinlma** [comment]
Thanks,Guy!
